name = "Bess"
uuid = "0f6bdffc-513a-42d2-9813-9a545800a63f"
authors = ["Himanshu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
